// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sayhi.ApiService.Data;

#nullable disable

namespace Sayhi.ApiService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sayhi.Model.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Agents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019ad1f0-ea6e-7f91-8183-e46e9d5ec70a"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(8942), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea6e-7c22-a334-7cce1f88f6e2"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(8945), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea6e-7b60-ab5a-8257002ead9f"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(8946), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea6e-700d-b474-234821ff8e2f"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(8947), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea6e-79c9-a1bb-47c4155b0e9c"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(8949), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea6e-775c-a176-e60c9a68542c"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(8950), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea6e-79d7-92ee-04f5e95b9edf"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(8953), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea6e-7b4f-aca9-16866828051d"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(8954), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = 0
                        });
                });

            modelBuilder.Entity("Sayhi.Model.AgentGroup", b =>
                {
                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AgentId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("AgentGroup");

                    b.HasData(
                        new
                        {
                            AgentId = new Guid("019ad1f0-ea6e-7f91-8183-e46e9d5ec70a"),
                            GroupId = new Guid("019ad1f0-ea71-7abf-88bb-8df92c9c0674"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(9137), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            AgentId = new Guid("019ad1f0-ea6e-7f91-8183-e46e9d5ec70a"),
                            GroupId = new Guid("019ad1f0-ea71-791e-87db-8ab1c436d107"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(9345), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            AgentId = new Guid("019ad1f0-ea6e-7f91-8183-e46e9d5ec70a"),
                            GroupId = new Guid("019ad1f0-ea71-7681-a705-1620498c3e79"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(9346), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            AgentId = new Guid("019ad1f0-ea6e-7f91-8183-e46e9d5ec70a"),
                            GroupId = new Guid("019ad1f0-ea71-7cf2-a6c4-6c7aad75ae42"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(9347), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            AgentId = new Guid("019ad1f0-ea6e-7f91-8183-e46e9d5ec70a"),
                            GroupId = new Guid("019ad1f0-ea71-792c-be1f-40e14b599af7"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(9348), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            AgentId = new Guid("019ad1f0-ea6e-7c22-a334-7cce1f88f6e2"),
                            GroupId = new Guid("019ad1f0-ea71-7abf-88bb-8df92c9c0674"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(9349), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            AgentId = new Guid("019ad1f0-ea6e-7c22-a334-7cce1f88f6e2"),
                            GroupId = new Guid("019ad1f0-ea71-791e-87db-8ab1c436d107"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(9357), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            AgentId = new Guid("019ad1f0-ea6e-7c22-a334-7cce1f88f6e2"),
                            GroupId = new Guid("019ad1f0-ea71-7681-a705-1620498c3e79"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(9358), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            AgentId = new Guid("019ad1f0-ea6e-7c22-a334-7cce1f88f6e2"),
                            GroupId = new Guid("019ad1f0-ea71-7cf2-a6c4-6c7aad75ae42"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(9359), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            AgentId = new Guid("019ad1f0-ea6e-7c22-a334-7cce1f88f6e2"),
                            GroupId = new Guid("019ad1f0-ea71-792c-be1f-40e14b599af7"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(9360), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            AgentId = new Guid("019ad1f0-ea6e-7b60-ab5a-8257002ead9f"),
                            GroupId = new Guid("019ad1f0-ea71-7abf-88bb-8df92c9c0674"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(9361), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            AgentId = new Guid("019ad1f0-ea6e-700d-b474-234821ff8e2f"),
                            GroupId = new Guid("019ad1f0-ea71-791e-87db-8ab1c436d107"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(9361), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            AgentId = new Guid("019ad1f0-ea6e-79c9-a1bb-47c4155b0e9c"),
                            GroupId = new Guid("019ad1f0-ea71-7681-a705-1620498c3e79"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(9362), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            AgentId = new Guid("019ad1f0-ea6e-775c-a176-e60c9a68542c"),
                            GroupId = new Guid("019ad1f0-ea71-7cf2-a6c4-6c7aad75ae42"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(9363), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            AgentId = new Guid("019ad1f0-ea6e-79d7-92ee-04f5e95b9edf"),
                            GroupId = new Guid("019ad1f0-ea71-792c-be1f-40e14b599af7"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(9364), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Sayhi.Model.AgentSkill", b =>
                {
                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CertifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<int>("Proficiency")
                        .HasColumnType("integer");

                    b.HasKey("AgentId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("AgentSkills");

                    b.HasData(
                        new
                        {
                            AgentId = new Guid("019ad1f0-ea6e-7f91-8183-e46e9d5ec70a"),
                            SkillId = new Guid("019ad1f0-ea71-722f-8c17-1d25e6cc8ec1"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(9522), new TimeSpan(0, 0, 0, 0, 0)),
                            IsPrimary = true,
                            Proficiency = 2
                        },
                        new
                        {
                            AgentId = new Guid("019ad1f0-ea6e-7c22-a334-7cce1f88f6e2"),
                            SkillId = new Guid("019ad1f0-ea71-722f-8c17-1d25e6cc8ec1"),
                            CertifiedAt = new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Utc).AddTicks(9885),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(9884), new TimeSpan(0, 0, 0, 0, 0)),
                            IsPrimary = true,
                            Proficiency = 2
                        },
                        new
                        {
                            AgentId = new Guid("019ad1f0-ea6e-7b60-ab5a-8257002ead9f"),
                            SkillId = new Guid("019ad1f0-ea71-7bb4-aae5-27a8374f29d0"),
                            CertifiedAt = new DateTime(2025, 5, 29, 23, 26, 58, 162, DateTimeKind.Utc).AddTicks(29),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 162, DateTimeKind.Unspecified).AddTicks(28), new TimeSpan(0, 0, 0, 0, 0)),
                            IsPrimary = false,
                            Proficiency = 1
                        },
                        new
                        {
                            AgentId = new Guid("019ad1f0-ea6e-700d-b474-234821ff8e2f"),
                            SkillId = new Guid("019ad1f0-ea71-7850-a6e1-5f682195dc75"),
                            CertifiedAt = new DateTime(2025, 8, 29, 23, 26, 58, 162, DateTimeKind.Utc).AddTicks(92),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 162, DateTimeKind.Unspecified).AddTicks(90), new TimeSpan(0, 0, 0, 0, 0)),
                            IsPrimary = false,
                            Proficiency = 0
                        });
                });

            modelBuilder.Entity("Sayhi.Model.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Chats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019ad1f0-ea6f-73cf-98ab-e13ad6826924"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 19, 46, 58, 159, DateTimeKind.Unspecified).AddTicks(243), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "",
                            Source = 3,
                            Tags = "{}"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea70-7602-8a24-9da0392a7cba"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 21, 16, 58, 160, DateTimeKind.Unspecified).AddTicks(7612), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "",
                            Source = 3,
                            Tags = "{\"Order\":0,\"Angry\":3}"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-72c4-80f6-9014ce8bec71"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 21, 56, 58, 161, DateTimeKind.Unspecified).AddTicks(3205), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "",
                            Source = 6,
                            Tags = "{\"Angry\":3,\"Order\":0}"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7a98-9d63-167f301a96fc"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 22, 6, 58, 161, DateTimeKind.Unspecified).AddTicks(3290), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "",
                            Source = 1,
                            Tags = "{\"Angry\":3}"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-777b-8f88-c4ab3e59cc82"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 22, 16, 58, 161, DateTimeKind.Unspecified).AddTicks(3305), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "",
                            Source = 6,
                            Tags = "{\"Angry\":3,\"Product\":2}"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7e39-8f13-c33ead528198"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 22, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(3349), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "",
                            Source = 3,
                            Tags = "{\"Angry\":3}"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7c06-bccf-81ded8025c48"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 22, 36, 58, 161, DateTimeKind.Unspecified).AddTicks(3358), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "",
                            Source = 5,
                            Tags = "{\"Product\":2,\"Angry\":3}"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-702e-9d87-300a3d457bbc"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 22, 46, 58, 161, DateTimeKind.Unspecified).AddTicks(3370), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "",
                            Source = 3,
                            Tags = "{\"Angry\":3}"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7fd8-a7bd-fb083e060277"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 22, 56, 58, 161, DateTimeKind.Unspecified).AddTicks(3381), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "",
                            Source = 5,
                            Tags = "{}"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7ca7-ba6c-f67be2e3e7ef"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 6, 58, 161, DateTimeKind.Unspecified).AddTicks(3393), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "",
                            Source = 2,
                            Tags = "{\"Order\":0,\"Product\":2}"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-73e2-93f7-b58f8710269e"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 16, 58, 161, DateTimeKind.Unspecified).AddTicks(3424), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "",
                            Source = 5,
                            Tags = "{}"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7b3a-964b-67ebdcaf3f2a"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(3615), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Bizim Elemanlar",
                            Source = 1,
                            Tags = "{\"Order\":0,\"Angry\":3,\"Product\":2}"
                        });
                });

            modelBuilder.Entity("Sayhi.Model.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("SenderId");

                    b.ToTable("ChatMessages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-70ac-90b7-1988cd0537a8"),
                            ChatId = new Guid("019ad1f0-ea6f-73cf-98ab-e13ad6826924"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 19, 42, 58, 161, DateTimeKind.Unspecified).AddTicks(4943), new TimeSpan(0, 0, 0, 0, 0)),
                            SenderId = new Guid("019ad1f0-ea6e-7c22-a334-7cce1f88f6e2"),
                            Status = 3,
                            Text = "Merhaba, projeyle ilgili bir sorum var"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7631-be57-185a943db3b4"),
                            ChatId = new Guid("019ad1f0-ea6f-73cf-98ab-e13ad6826924"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 19, 43, 58, 161, DateTimeKind.Unspecified).AddTicks(5047), new TimeSpan(0, 0, 0, 0, 0)),
                            SenderId = new Guid("019ad1f0-ea6e-7f91-8183-e46e9d5ec70a"),
                            Status = 3,
                            Text = "Merhaba Ahmet! Tabii, buyurun sorun"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7fe6-82db-8e9f40ff0da4"),
                            ChatId = new Guid("019ad1f0-ea6f-73cf-98ab-e13ad6826924"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 19, 44, 58, 161, DateTimeKind.Unspecified).AddTicks(5049), new TimeSpan(0, 0, 0, 0, 0)),
                            SenderId = new Guid("019ad1f0-ea6e-7c22-a334-7cce1f88f6e2"),
                            Status = 2,
                            Text = "Tasarım dosyalarını ne zaman paylaşabilirsiniz?"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7a4a-857b-ca9c0fe430cd"),
                            ChatId = new Guid("019ad1f0-ea6f-73cf-98ab-e13ad6826924"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 19, 45, 58, 161, DateTimeKind.Unspecified).AddTicks(5052), new TimeSpan(0, 0, 0, 0, 0)),
                            SenderId = new Guid("019ad1f0-ea6e-7f91-8183-e46e9d5ec70a"),
                            Status = 1,
                            Text = "Bugün sonu itibariyle tüm dosyaları paylaşacağım. PDF ve Figma linklerini göndereceğim."
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7d34-a3f5-702536521292"),
                            ChatId = new Guid("019ad1f0-ea6f-73cf-98ab-e13ad6826924"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 19, 46, 58, 161, DateTimeKind.Unspecified).AddTicks(5054), new TimeSpan(0, 0, 0, 0, 0)),
                            SenderId = new Guid("019ad1f0-ea6e-7c22-a334-7cce1f88f6e2"),
                            Status = 1,
                            Text = "Harika! Projeyi ne zaman teslim edebiliriz?"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7496-b843-f6399e909fcd"),
                            ChatId = new Guid("019ad1f0-ea70-7602-8a24-9da0392a7cba"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 21, 15, 58, 161, DateTimeKind.Unspecified).AddTicks(5056), new TimeSpan(0, 0, 0, 0, 0)),
                            SenderId = new Guid("019ad1f0-ea6e-7b60-ab5a-8257002ead9f"),
                            Status = 3,
                            Text = "Lütfen adamı hasta etmeyelim."
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7718-a547-9af232b5b4a3"),
                            ChatId = new Guid("019ad1f0-ea70-7602-8a24-9da0392a7cba"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 21, 16, 58, 161, DateTimeKind.Unspecified).AddTicks(5058), new TimeSpan(0, 0, 0, 0, 0)),
                            SenderId = new Guid("019ad1f0-ea6e-7f91-8183-e46e9d5ec70a"),
                            Status = 1,
                            Text = "Tabiki efem"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-76e4-8702-32088a877f17"),
                            ChatId = new Guid("019ad1f0-ea71-72c4-80f6-9014ce8bec71"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 22, 54, 58, 161, DateTimeKind.Unspecified).AddTicks(5063), new TimeSpan(0, 0, 0, 0, 0)),
                            SenderId = new Guid("019ad1f0-ea6e-700d-b474-234821ff8e2f"),
                            Status = 3,
                            Text = "Abüzüpler pırızıttı mı?."
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7493-8691-fa24b970d04d"),
                            ChatId = new Guid("019ad1f0-ea71-72c4-80f6-9014ce8bec71"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 22, 55, 58, 161, DateTimeKind.Unspecified).AddTicks(5066), new TimeSpan(0, 0, 0, 0, 0)),
                            SenderId = new Guid("019ad1f0-ea6e-7f91-8183-e46e9d5ec70a"),
                            Status = 1,
                            Text = "Efendim?!"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7ac7-8c0d-82c29797a58c"),
                            ChatId = new Guid("019ad1f0-ea71-72c4-80f6-9014ce8bec71"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 22, 56, 58, 161, DateTimeKind.Unspecified).AddTicks(5076), new TimeSpan(0, 0, 0, 0, 0)),
                            SenderId = new Guid("019ad1f0-ea6e-700d-b474-234821ff8e2f"),
                            Status = 1,
                            Text = "Zıırt Erenköy :)"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-71da-8c14-bf4df652c25e"),
                            ChatId = new Guid("019ad1f0-ea71-7a98-9d63-167f301a96fc"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 22, 55, 58, 161, DateTimeKind.Unspecified).AddTicks(5078), new TimeSpan(0, 0, 0, 0, 0)),
                            SenderId = new Guid("019ad1f0-ea6e-7f91-8183-e46e9d5ec70a"),
                            Status = 1,
                            Text = "Asl pls!"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-71a7-971b-bde29319a12c"),
                            ChatId = new Guid("019ad1f0-ea71-7a98-9d63-167f301a96fc"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 22, 56, 58, 161, DateTimeKind.Unspecified).AddTicks(5103), new TimeSpan(0, 0, 0, 0, 0)),
                            SenderId = new Guid("019ad1f0-ea6e-79c9-a1bb-47c4155b0e9c"),
                            Status = 1,
                            Text = "18 f izmir"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7a3f-8c71-b382f6c6aca3"),
                            ChatId = new Guid("019ad1f0-ea71-777b-8f88-c4ab3e59cc82"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 22, 55, 58, 161, DateTimeKind.Unspecified).AddTicks(5106), new TimeSpan(0, 0, 0, 0, 0)),
                            SenderId = new Guid("019ad1f0-ea6e-7f91-8183-e46e9d5ec70a"),
                            Status = 1,
                            Text = "Aloo"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7ff3-948c-955cc543a987"),
                            ChatId = new Guid("019ad1f0-ea71-777b-8f88-c4ab3e59cc82"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 22, 56, 58, 161, DateTimeKind.Unspecified).AddTicks(5108), new TimeSpan(0, 0, 0, 0, 0)),
                            SenderId = new Guid("019ad1f0-ea6e-775c-a176-e60c9a68542c"),
                            Status = 1,
                            Text = "Ne diyon?"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-77d6-89e1-c7b716aea03a"),
                            ChatId = new Guid("019ad1f0-ea71-7e39-8f13-c33ead528198"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 22, 55, 58, 161, DateTimeKind.Unspecified).AddTicks(5110), new TimeSpan(0, 0, 0, 0, 0)),
                            SenderId = new Guid("019ad1f0-ea6e-7f91-8183-e46e9d5ec70a"),
                            Status = 1,
                            Text = "merhaba"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7c7f-813f-52e81490723f"),
                            ChatId = new Guid("019ad1f0-ea71-7e39-8f13-c33ead528198"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 22, 56, 58, 161, DateTimeKind.Unspecified).AddTicks(5114), new TimeSpan(0, 0, 0, 0, 0)),
                            SenderId = new Guid("019ad1f0-ea6e-79d7-92ee-04f5e95b9edf"),
                            Status = 1,
                            Text = "he"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7c8e-8a8d-305b28083ffb"),
                            ChatId = new Guid("019ad1f0-ea71-7c06-bccf-81ded8025c48"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 22, 55, 58, 161, DateTimeKind.Unspecified).AddTicks(5116), new TimeSpan(0, 0, 0, 0, 0)),
                            SenderId = new Guid("019ad1f0-ea6e-7f91-8183-e46e9d5ec70a"),
                            Status = 1,
                            Text = "selam"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7796-960c-41f385e1204b"),
                            ChatId = new Guid("019ad1f0-ea71-7c06-bccf-81ded8025c48"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 22, 56, 58, 161, DateTimeKind.Unspecified).AddTicks(5118), new TimeSpan(0, 0, 0, 0, 0)),
                            SenderId = new Guid("019ad1f0-ea6e-7b4f-aca9-16866828051d"),
                            Status = 1,
                            Text = "sucuk"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7050-bc9c-677babb49a22"),
                            ChatId = new Guid("019ad1f0-ea71-702e-9d87-300a3d457bbc"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 22, 55, 58, 161, DateTimeKind.Unspecified).AddTicks(5120), new TimeSpan(0, 0, 0, 0, 0)),
                            SenderId = new Guid("019ad1f0-ea6e-7c22-a334-7cce1f88f6e2"),
                            Status = 1,
                            Text = "Abuzer"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-725a-9428-0479dd574263"),
                            ChatId = new Guid("019ad1f0-ea71-702e-9d87-300a3d457bbc"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 22, 56, 58, 161, DateTimeKind.Unspecified).AddTicks(5122), new TimeSpan(0, 0, 0, 0, 0)),
                            SenderId = new Guid("019ad1f0-ea6e-7b60-ab5a-8257002ead9f"),
                            Status = 1,
                            Text = "Kadayıf"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7a65-acfd-a2928a908885"),
                            ChatId = new Guid("019ad1f0-ea71-7fd8-a7bd-fb083e060277"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 22, 55, 58, 161, DateTimeKind.Unspecified).AddTicks(5124), new TimeSpan(0, 0, 0, 0, 0)),
                            SenderId = new Guid("019ad1f0-ea6e-7c22-a334-7cce1f88f6e2"),
                            Status = 1,
                            Text = "1 chat kaç para ulen!?"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7df9-90e3-1ac423ce2b9a"),
                            ChatId = new Guid("019ad1f0-ea71-7fd8-a7bd-fb083e060277"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 22, 56, 58, 161, DateTimeKind.Unspecified).AddTicks(5127), new TimeSpan(0, 0, 0, 0, 0)),
                            SenderId = new Guid("019ad1f0-ea6e-700d-b474-234821ff8e2f"),
                            Status = 1,
                            Text = ":)"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7190-9e54-014febd3ecc9"),
                            ChatId = new Guid("019ad1f0-ea71-7ca7-ba6c-f67be2e3e7ef"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 22, 55, 58, 161, DateTimeKind.Unspecified).AddTicks(5135), new TimeSpan(0, 0, 0, 0, 0)),
                            SenderId = new Guid("019ad1f0-ea6e-7c22-a334-7cce1f88f6e2"),
                            Status = 1,
                            Text = "Kimsin?"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-71bf-b80a-3e6162444178"),
                            ChatId = new Guid("019ad1f0-ea71-7ca7-ba6c-f67be2e3e7ef"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 22, 56, 58, 161, DateTimeKind.Unspecified).AddTicks(5139), new TimeSpan(0, 0, 0, 0, 0)),
                            SenderId = new Guid("019ad1f0-ea6e-7b4f-aca9-16866828051d"),
                            Status = 1,
                            Text = "Benim."
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-736b-870a-e39cbf214d10"),
                            ChatId = new Guid("019ad1f0-ea71-73e2-93f7-b58f8710269e"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 22, 55, 58, 161, DateTimeKind.Unspecified).AddTicks(5141), new TimeSpan(0, 0, 0, 0, 0)),
                            SenderId = new Guid("019ad1f0-ea6e-7b60-ab5a-8257002ead9f"),
                            Status = 1,
                            Text = "???"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-71e1-9099-2f61f653e8e1"),
                            ChatId = new Guid("019ad1f0-ea71-73e2-93f7-b58f8710269e"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 22, 56, 58, 161, DateTimeKind.Unspecified).AddTicks(5143), new TimeSpan(0, 0, 0, 0, 0)),
                            SenderId = new Guid("019ad1f0-ea6e-700d-b474-234821ff8e2f"),
                            Status = 1,
                            Text = "!!!"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7bea-a0bf-80108bc9cb0c"),
                            ChatId = new Guid("019ad1f0-ea71-7b3a-964b-67ebdcaf3f2a"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 22, 55, 58, 161, DateTimeKind.Unspecified).AddTicks(5146), new TimeSpan(0, 0, 0, 0, 0)),
                            SenderId = new Guid("019ad1f0-ea6e-7f91-8183-e46e9d5ec70a"),
                            Status = 1,
                            Text = "Selam millet"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7b4d-8a58-edf0b32b3fcd"),
                            ChatId = new Guid("019ad1f0-ea71-7b3a-964b-67ebdcaf3f2a"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 22, 55, 58, 161, DateTimeKind.Unspecified).AddTicks(5148), new TimeSpan(0, 0, 0, 0, 0)),
                            SenderId = new Guid("019ad1f0-ea6e-7f91-8183-e46e9d5ec70a"),
                            Status = 1,
                            Text = "Naabıyonuz?"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7ec5-bad0-a5591ce83f51"),
                            ChatId = new Guid("019ad1f0-ea71-7b3a-964b-67ebdcaf3f2a"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 22, 55, 58, 161, DateTimeKind.Unspecified).AddTicks(5150), new TimeSpan(0, 0, 0, 0, 0)),
                            SenderId = new Guid("019ad1f0-ea6e-7f91-8183-e46e9d5ec70a"),
                            Status = 1,
                            Text = "Keyifler gıcır mı?"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7c9f-9058-6fed48e33430"),
                            ChatId = new Guid("019ad1f0-ea71-7b3a-964b-67ebdcaf3f2a"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 22, 55, 58, 161, DateTimeKind.Unspecified).AddTicks(5153), new TimeSpan(0, 0, 0, 0, 0)),
                            SenderId = new Guid("019ad1f0-ea6e-7c22-a334-7cce1f88f6e2"),
                            Status = 1,
                            Text = "Merabayın"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7a5c-85d3-f7bddbe88526"),
                            ChatId = new Guid("019ad1f0-ea71-7b3a-964b-67ebdcaf3f2a"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 22, 55, 58, 161, DateTimeKind.Unspecified).AddTicks(5155), new TimeSpan(0, 0, 0, 0, 0)),
                            SenderId = new Guid("019ad1f0-ea6e-7c22-a334-7cce1f88f6e2"),
                            Status = 1,
                            Text = "Takılmaca"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7fef-a6ca-9ec2b12312ab"),
                            ChatId = new Guid("019ad1f0-ea71-7b3a-964b-67ebdcaf3f2a"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 22, 55, 58, 161, DateTimeKind.Unspecified).AddTicks(5158), new TimeSpan(0, 0, 0, 0, 0)),
                            SenderId = new Guid("019ad1f0-ea6e-7b60-ab5a-8257002ead9f"),
                            Status = 1,
                            Text = "Devamke"
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7594-9b02-d6f3febab8e0"),
                            ChatId = new Guid("019ad1f0-ea71-7b3a-964b-67ebdcaf3f2a"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 22, 56, 58, 161, DateTimeKind.Unspecified).AddTicks(5160), new TimeSpan(0, 0, 0, 0, 0)),
                            SenderId = new Guid("019ad1f0-ea6e-700d-b474-234821ff8e2f"),
                            Status = 1,
                            Text = "Lorke lorke..."
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-77c8-ad12-115fb6a1292d"),
                            ChatId = new Guid("019ad1f0-ea71-7b3a-964b-67ebdcaf3f2a"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 22, 56, 58, 161, DateTimeKind.Unspecified).AddTicks(5162), new TimeSpan(0, 0, 0, 0, 0)),
                            SenderId = new Guid("019ad1f0-ea6e-700d-b474-234821ff8e2f"),
                            Status = 1,
                            Text = "Delalım lorke"
                        });
                });

            modelBuilder.Entity("Sayhi.Model.ChatParticipant", b =>
                {
                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ChatId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("ChatParticipants");

                    b.HasData(
                        new
                        {
                            ChatId = new Guid("019ad1f0-ea6f-73cf-98ab-e13ad6826924"),
                            PersonId = new Guid("019ad1f0-ea6e-7f91-8183-e46e9d5ec70a"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(3976), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ChatId = new Guid("019ad1f0-ea6f-73cf-98ab-e13ad6826924"),
                            PersonId = new Guid("019ad1f0-ea6e-7c22-a334-7cce1f88f6e2"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(4391), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ChatId = new Guid("019ad1f0-ea70-7602-8a24-9da0392a7cba"),
                            PersonId = new Guid("019ad1f0-ea6e-7f91-8183-e46e9d5ec70a"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(4392), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ChatId = new Guid("019ad1f0-ea70-7602-8a24-9da0392a7cba"),
                            PersonId = new Guid("019ad1f0-ea6e-7b60-ab5a-8257002ead9f"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(4393), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ChatId = new Guid("019ad1f0-ea71-72c4-80f6-9014ce8bec71"),
                            PersonId = new Guid("019ad1f0-ea6e-7f91-8183-e46e9d5ec70a"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(4394), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ChatId = new Guid("019ad1f0-ea71-72c4-80f6-9014ce8bec71"),
                            PersonId = new Guid("019ad1f0-ea6e-700d-b474-234821ff8e2f"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(4394), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ChatId = new Guid("019ad1f0-ea71-7a98-9d63-167f301a96fc"),
                            PersonId = new Guid("019ad1f0-ea6e-7f91-8183-e46e9d5ec70a"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(4395), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ChatId = new Guid("019ad1f0-ea71-7a98-9d63-167f301a96fc"),
                            PersonId = new Guid("019ad1f0-ea6e-79c9-a1bb-47c4155b0e9c"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(4396), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ChatId = new Guid("019ad1f0-ea71-777b-8f88-c4ab3e59cc82"),
                            PersonId = new Guid("019ad1f0-ea6e-7f91-8183-e46e9d5ec70a"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(4397), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ChatId = new Guid("019ad1f0-ea71-777b-8f88-c4ab3e59cc82"),
                            PersonId = new Guid("019ad1f0-ea6e-775c-a176-e60c9a68542c"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(4398), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ChatId = new Guid("019ad1f0-ea71-7e39-8f13-c33ead528198"),
                            PersonId = new Guid("019ad1f0-ea6e-7f91-8183-e46e9d5ec70a"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(4398), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ChatId = new Guid("019ad1f0-ea71-7e39-8f13-c33ead528198"),
                            PersonId = new Guid("019ad1f0-ea6e-79d7-92ee-04f5e95b9edf"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(4399), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ChatId = new Guid("019ad1f0-ea71-7c06-bccf-81ded8025c48"),
                            PersonId = new Guid("019ad1f0-ea6e-7f91-8183-e46e9d5ec70a"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(4400), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ChatId = new Guid("019ad1f0-ea71-7c06-bccf-81ded8025c48"),
                            PersonId = new Guid("019ad1f0-ea6e-7b4f-aca9-16866828051d"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(4401), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ChatId = new Guid("019ad1f0-ea71-702e-9d87-300a3d457bbc"),
                            PersonId = new Guid("019ad1f0-ea6e-7c22-a334-7cce1f88f6e2"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(4401), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ChatId = new Guid("019ad1f0-ea71-702e-9d87-300a3d457bbc"),
                            PersonId = new Guid("019ad1f0-ea6e-7b60-ab5a-8257002ead9f"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(4402), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ChatId = new Guid("019ad1f0-ea71-7fd8-a7bd-fb083e060277"),
                            PersonId = new Guid("019ad1f0-ea6e-7c22-a334-7cce1f88f6e2"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(4403), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ChatId = new Guid("019ad1f0-ea71-7fd8-a7bd-fb083e060277"),
                            PersonId = new Guid("019ad1f0-ea6e-700d-b474-234821ff8e2f"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(4404), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ChatId = new Guid("019ad1f0-ea71-7ca7-ba6c-f67be2e3e7ef"),
                            PersonId = new Guid("019ad1f0-ea6e-7c22-a334-7cce1f88f6e2"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(4405), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ChatId = new Guid("019ad1f0-ea71-7ca7-ba6c-f67be2e3e7ef"),
                            PersonId = new Guid("019ad1f0-ea6e-7b4f-aca9-16866828051d"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(4405), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ChatId = new Guid("019ad1f0-ea71-73e2-93f7-b58f8710269e"),
                            PersonId = new Guid("019ad1f0-ea6e-7b60-ab5a-8257002ead9f"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(4406), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ChatId = new Guid("019ad1f0-ea71-73e2-93f7-b58f8710269e"),
                            PersonId = new Guid("019ad1f0-ea6e-700d-b474-234821ff8e2f"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(4407), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ChatId = new Guid("019ad1f0-ea71-7b3a-964b-67ebdcaf3f2a"),
                            PersonId = new Guid("019ad1f0-ea6e-7f91-8183-e46e9d5ec70a"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(4415), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ChatId = new Guid("019ad1f0-ea71-7b3a-964b-67ebdcaf3f2a"),
                            PersonId = new Guid("019ad1f0-ea6e-7c22-a334-7cce1f88f6e2"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(4416), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ChatId = new Guid("019ad1f0-ea71-7b3a-964b-67ebdcaf3f2a"),
                            PersonId = new Guid("019ad1f0-ea6e-7b60-ab5a-8257002ead9f"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(4417), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ChatId = new Guid("019ad1f0-ea71-7b3a-964b-67ebdcaf3f2a"),
                            PersonId = new Guid("019ad1f0-ea6e-700d-b474-234821ff8e2f"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(4418), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Sayhi.Model.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Type");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7abf-88bb-8df92c9c0674"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(5829), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Müşteri satış ve ürün bilgilendirme ekibi",
                            IsActive = true,
                            Name = "Satış Ekibi",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-791e-87db-8ab1c436d107"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(6217), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Yazılım ve donanım teknik destek ekibi",
                            IsActive = true,
                            Name = "Teknik Destek",
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7681-a705-1620498c3e79"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(6219), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Genel müşteri şikayet ve talepleri ekibi",
                            IsActive = true,
                            Name = "Müşteri Hizmetleri",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7cf2-a6c4-6c7aad75ae42"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(6220), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Kurumsal ve premium müşterilere özel destek",
                            IsActive = true,
                            Name = "VIP Destek",
                            Type = 4
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-792c-be1f-40e14b599af7"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(6221), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Takım liderleri ve call center yöneticileri",
                            IsActive = true,
                            Name = "Call Center Yönetimi",
                            Type = 5
                        });
                });

            modelBuilder.Entity("Sayhi.Model.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000041"),
                            AvatarUrl = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 157, DateTimeKind.Unspecified).AddTicks(5868), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "ai@nomail.com",
                            Name = "ai",
                            Password = "C4CA4238A0B923820DCC509A6F75849B",
                            PhoneNumber = ""
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea6e-7f91-8183-e46e9d5ec70a"),
                            AvatarUrl = "https://0.gravatar.com/avatar/b42f914d14fdd06440f626ee2d8e68c5fe4fb4c5f97386ac12ad0267edbcd8fc",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 158, DateTimeKind.Unspecified).AddTicks(5438), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "ozgur.civi@outlook.com",
                            Name = "Özgür Çivi",
                            Password = "C4CA4238A0B923820DCC509A6F75849B",
                            PhoneNumber = ""
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea6e-7c22-a334-7cce1f88f6e2"),
                            AvatarUrl = "https://api.dicebear.com/7.x/avataaars/svg?seed=Mikail",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 158, DateTimeKind.Unspecified).AddTicks(5728), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "ozgur.civi@gmail.com",
                            Name = "Mikail Çivi",
                            Password = "C4CA4238A0B923820DCC509A6F75849B",
                            PhoneNumber = ""
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea6e-7b60-ab5a-8257002ead9f"),
                            AvatarUrl = "https://api.dicebear.com/7.x/avataaars/svg?seed=Timur",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 158, DateTimeKind.Unspecified).AddTicks(5737), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "ozgur_civi@yahoo.com",
                            Name = "Timur Çivi",
                            Password = "C4CA4238A0B923820DCC509A6F75849B",
                            PhoneNumber = ""
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea6e-700d-b474-234821ff8e2f"),
                            AvatarUrl = "https://api.dicebear.com/7.x/avataaars/svg?seed=Gueven",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 158, DateTimeKind.Unspecified).AddTicks(5759), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "ozgur.civi@yubis.com",
                            Name = "Güven Çivi",
                            Password = "C4CA4238A0B923820DCC509A6F75849B",
                            PhoneNumber = ""
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea6e-79c9-a1bb-47c4155b0e9c"),
                            AvatarUrl = "https://api.dicebear.com/7.x/avataaars/svg?seed=Mehmet",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 158, DateTimeKind.Unspecified).AddTicks(5765), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "mehmet.kaya@yubis.com",
                            Name = "Mehmet Kaya",
                            Password = "A87FF679A2F3E71D9181A67B7542122C",
                            PhoneNumber = ""
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea6e-775c-a176-e60c9a68542c"),
                            AvatarUrl = "https://api.dicebear.com/7.x/avataaars/svg?seed=Ahmet",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 158, DateTimeKind.Unspecified).AddTicks(5772), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "jitewaboh@lagify.com",
                            Name = "Ahmet Yılmaz",
                            Password = "C81E728D9D4C2F636F067F89CC14862C",
                            PhoneNumber = ""
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea6e-79d7-92ee-04f5e95b9edf"),
                            AvatarUrl = "https://api.dicebear.com/7.x/avataaars/svg?seed=Ayse",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 158, DateTimeKind.Unspecified).AddTicks(5778), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "aysed@outlook.com",
                            Name = "Ayşe Demir",
                            Password = "ECCBC87E4B5CE2FE28308FD9F2A7BAF3",
                            PhoneNumber = ""
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea6e-7b4f-aca9-16866828051d"),
                            AvatarUrl = "https://api.dicebear.com/7.x/avataaars/svg?seed=Zeynep",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 158, DateTimeKind.Unspecified).AddTicks(5812), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "zeynep.sahin@gmail.com",
                            Name = "Zeynep Şahin",
                            Password = "E4DA3B7FBBCE2345D7772B0674A318D5",
                            PhoneNumber = ""
                        });
                });

            modelBuilder.Entity("Sayhi.Model.Queue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxConcurrentCalls")
                        .HasColumnType("integer");

                    b.Property<int>("MaxWaitTime")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Type");

                    b.ToTable("Queues");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-79e5-9942-6527eabe0b5e"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(6747), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Tüm gelen müşteri çağrıları için ana kuyruk",
                            GroupId = new Guid("019ad1f0-ea71-7681-a705-1620498c3e79"),
                            IsActive = true,
                            MaxConcurrentCalls = 20,
                            MaxWaitTime = 180,
                            Name = "Gelen_Çağrılar_Ana",
                            Priority = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7016-8c82-236391c23afb"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(7642), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Yazılım ve teknik problemler için özel kuyruk",
                            GroupId = new Guid("019ad1f0-ea71-791e-87db-8ab1c436d107"),
                            IsActive = true,
                            MaxConcurrentCalls = 15,
                            MaxWaitTime = 300,
                            Name = "Teknik_Destek",
                            Priority = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-79ac-968c-e03a1c268a6d"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(7645), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Kurumsal ve premium müşterilere öncelikli kuyruk",
                            GroupId = new Guid("019ad1f0-ea71-7cf2-a6c4-6c7aad75ae42"),
                            IsActive = true,
                            MaxConcurrentCalls = 10,
                            MaxWaitTime = 60,
                            Name = "VIP_Müşteriler",
                            Priority = 1,
                            Type = 5
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-773a-ba44-9e8aac796dbb"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(7648), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Müşteri taleplerine göre planlanan geri aramalar",
                            GroupId = new Guid("019ad1f0-ea71-7abf-88bb-8df92c9c0674"),
                            IsActive = true,
                            MaxConcurrentCalls = 5,
                            MaxWaitTime = 86400,
                            Name = "Geri_Arama",
                            Priority = 3,
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7340-9021-a42838d62798"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(7650), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Potansiyel müşterilere yapılan satış çağrıları",
                            GroupId = new Guid("019ad1f0-ea71-7abf-88bb-8df92c9c0674"),
                            IsActive = true,
                            MaxConcurrentCalls = 25,
                            MaxWaitTime = 120,
                            Name = "Satış_Giden_Çağrılar",
                            Priority = 2,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7a4c-8ea1-9bfac22cea62"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(7652), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Kritik ve acil durumlar için öncelikli kuyruk",
                            GroupId = new Guid("019ad1f0-ea71-791e-87db-8ab1c436d107"),
                            IsActive = true,
                            MaxConcurrentCalls = 8,
                            MaxWaitTime = 45,
                            Name = "Öncelikli_Destek",
                            Priority = 1,
                            Type = 4
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7788-999c-334468550244"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(7655), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Fatura sorgulama ve ödeme problemleri kuyruğu",
                            GroupId = new Guid("019ad1f0-ea71-7681-a705-1620498c3e79"),
                            IsActive = true,
                            MaxConcurrentCalls = 12,
                            MaxWaitTime = 240,
                            Name = "Fatura_Ödeme",
                            Priority = 2,
                            Type = 1
                        });
                });

            modelBuilder.Entity("Sayhi.Model.QueueAssignment", b =>
                {
                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QueueId")
                        .HasColumnType("uuid");

                    b.Property<double>("AverageHandleTime")
                        .HasColumnType("double precision");

                    b.Property<int>("CallsHandled")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<double>("SatisfactionScore")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("UnassignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AgentId", "QueueId");

                    b.HasIndex("QueueId");

                    b.ToTable("QueueAssignments");

                    b.HasData(
                        new
                        {
                            AgentId = new Guid("019ad1f0-ea6e-7f91-8183-e46e9d5ec70a"),
                            QueueId = new Guid("019ad1f0-ea71-79e5-9942-6527eabe0b5e"),
                            AverageHandleTime = 0.0,
                            CallsHandled = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 162, DateTimeKind.Unspecified).AddTicks(297), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = 1,
                            SatisfactionScore = 0.0
                        },
                        new
                        {
                            AgentId = new Guid("019ad1f0-ea6e-7c22-a334-7cce1f88f6e2"),
                            QueueId = new Guid("019ad1f0-ea71-79e5-9942-6527eabe0b5e"),
                            AverageHandleTime = 0.0,
                            CallsHandled = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 162, DateTimeKind.Unspecified).AddTicks(585), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = 1,
                            SatisfactionScore = 0.0
                        },
                        new
                        {
                            AgentId = new Guid("019ad1f0-ea6e-7b60-ab5a-8257002ead9f"),
                            QueueId = new Guid("019ad1f0-ea71-79e5-9942-6527eabe0b5e"),
                            AverageHandleTime = 0.0,
                            CallsHandled = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 162, DateTimeKind.Unspecified).AddTicks(587), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = 1,
                            SatisfactionScore = 0.0
                        },
                        new
                        {
                            AgentId = new Guid("019ad1f0-ea6e-700d-b474-234821ff8e2f"),
                            QueueId = new Guid("019ad1f0-ea71-79e5-9942-6527eabe0b5e"),
                            AverageHandleTime = 0.0,
                            CallsHandled = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 162, DateTimeKind.Unspecified).AddTicks(587), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = 1,
                            SatisfactionScore = 0.0
                        },
                        new
                        {
                            AgentId = new Guid("019ad1f0-ea6e-7f91-8183-e46e9d5ec70a"),
                            QueueId = new Guid("019ad1f0-ea71-7340-9021-a42838d62798"),
                            AverageHandleTime = 0.0,
                            CallsHandled = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 162, DateTimeKind.Unspecified).AddTicks(588), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = 1,
                            SatisfactionScore = 0.0
                        },
                        new
                        {
                            AgentId = new Guid("019ad1f0-ea6e-7c22-a334-7cce1f88f6e2"),
                            QueueId = new Guid("019ad1f0-ea71-7340-9021-a42838d62798"),
                            AverageHandleTime = 0.0,
                            CallsHandled = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 162, DateTimeKind.Unspecified).AddTicks(589), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = 1,
                            SatisfactionScore = 0.0
                        },
                        new
                        {
                            AgentId = new Guid("019ad1f0-ea6e-7f91-8183-e46e9d5ec70a"),
                            QueueId = new Guid("019ad1f0-ea71-773a-ba44-9e8aac796dbb"),
                            AverageHandleTime = 0.0,
                            CallsHandled = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 162, DateTimeKind.Unspecified).AddTicks(590), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = 1,
                            SatisfactionScore = 0.0
                        },
                        new
                        {
                            AgentId = new Guid("019ad1f0-ea6e-79c9-a1bb-47c4155b0e9c"),
                            QueueId = new Guid("019ad1f0-ea71-7016-8c82-236391c23afb"),
                            AverageHandleTime = 0.0,
                            CallsHandled = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 162, DateTimeKind.Unspecified).AddTicks(591), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = 1,
                            SatisfactionScore = 0.0
                        },
                        new
                        {
                            AgentId = new Guid("019ad1f0-ea6e-775c-a176-e60c9a68542c"),
                            QueueId = new Guid("019ad1f0-ea71-79ac-968c-e03a1c268a6d"),
                            AverageHandleTime = 0.0,
                            CallsHandled = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 162, DateTimeKind.Unspecified).AddTicks(592), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = 1,
                            SatisfactionScore = 0.0
                        });
                });

            modelBuilder.Entity("Sayhi.Model.QueueSkill", b =>
                {
                    b.Property<Guid>("QueueId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<int>("MinimumProficiency")
                        .HasColumnType("integer");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("QueueId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("QueueSkills");

                    b.HasData(
                        new
                        {
                            QueueId = new Guid("019ad1f0-ea71-7016-8c82-236391c23afb"),
                            SkillId = new Guid("019ad1f0-ea71-7bb4-aae5-27a8374f29d0"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 162, DateTimeKind.Unspecified).AddTicks(796), new TimeSpan(0, 0, 0, 0, 0)),
                            IsRequired = true,
                            MinimumProficiency = 1,
                            Weight = 10
                        },
                        new
                        {
                            QueueId = new Guid("019ad1f0-ea71-79ac-968c-e03a1c268a6d"),
                            SkillId = new Guid("019ad1f0-ea71-7eec-be64-0881e762964c"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 162, DateTimeKind.Unspecified).AddTicks(1263), new TimeSpan(0, 0, 0, 0, 0)),
                            IsRequired = true,
                            MinimumProficiency = 2,
                            Weight = 10
                        },
                        new
                        {
                            QueueId = new Guid("019ad1f0-ea71-7340-9021-a42838d62798"),
                            SkillId = new Guid("019ad1f0-ea71-7850-a6e1-5f682195dc75"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 162, DateTimeKind.Unspecified).AddTicks(1265), new TimeSpan(0, 0, 0, 0, 0)),
                            IsRequired = false,
                            MinimumProficiency = 0,
                            Weight = 8
                        });
                });

            modelBuilder.Entity("Sayhi.Model.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-722f-8c17-1d25e6cc8ec1"),
                            Category = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(8100), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "İngilizce müşteri iletişim yeteneği",
                            IsActive = true,
                            Name = "İngilizce",
                            Priority = 1
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7bb4-aae5-27a8374f29d0"),
                            Category = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(8560), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Yazılım ve donanım teknik problem çözme yeteneği",
                            IsActive = true,
                            Name = "Teknik Destek",
                            Priority = 2
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7850-a6e1-5f682195dc75"),
                            Category = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(8562), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Müşteri ikna ve ürün satış yeteneği",
                            IsActive = true,
                            Name = "Satış ve İkna",
                            Priority = 1
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7936-92c8-536de9a45bc1"),
                            Category = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(8570), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Fatura sorgulama ve ödeme sistemleri bilgisi",
                            IsActive = true,
                            Name = "Fatura Sistemi",
                            Priority = 2
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7c5a-b0c6-219e8b4b9892"),
                            Category = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(8572), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Müşteri ilişkileri yönetim sistemleri kullanım bilgisi",
                            IsActive = true,
                            Name = "CRM Sistemleri",
                            Priority = 3
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7447-83a3-a3be048b964a"),
                            Category = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(8573), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Almanca müşteri iletişim yeteneği",
                            IsActive = true,
                            Name = "Almanca",
                            Priority = 2
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7a50-badc-7c79c7ea8170"),
                            Category = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(8575), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Türkçe müşteri iletişim yeteneği",
                            IsActive = true,
                            Name = "Türkçe",
                            Priority = 3
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-775e-9410-266e890e5549"),
                            Category = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(8593), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Ağ bağlantı problemlerini çözme yeteneği",
                            IsActive = true,
                            Name = "Network Sorun Giderme",
                            Priority = 2
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7c98-9e6c-0a35cb8e170b"),
                            Category = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(8595), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Yazılım kurulum ve yapılandırma bilgisi",
                            IsActive = true,
                            Name = "Yazılım Kurulumu",
                            Priority = 3
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-7eec-be64-0881e762964c"),
                            Category = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(8597), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Kurumsal ve premium müşteri ilişkileri yönetimi",
                            IsActive = true,
                            Name = "VIP Müşteri Yönetimi",
                            Priority = 1
                        },
                        new
                        {
                            Id = new Guid("019ad1f0-ea71-742d-9bb7-40d7c3a2985a"),
                            Category = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 29, 23, 26, 58, 161, DateTimeKind.Unspecified).AddTicks(8599), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Karmaşık müşteri problemlerini analiz etme ve çözme",
                            IsActive = true,
                            Name = "Problem Çözme",
                            Priority = 1
                        });
                });

            modelBuilder.Entity("Sayhi.Model.Agent", b =>
                {
                    b.HasOne("Sayhi.Model.Person", "Person")
                        .WithOne("Agent")
                        .HasForeignKey("Sayhi.Model.Agent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Sayhi.Model.AgentGroup", b =>
                {
                    b.HasOne("Sayhi.Model.Agent", "Agent")
                        .WithMany("AgentGroups")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sayhi.Model.Group", "Group")
                        .WithMany("AgentGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Sayhi.Model.AgentSkill", b =>
                {
                    b.HasOne("Sayhi.Model.Agent", "Agent")
                        .WithMany("AgentSkills")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sayhi.Model.Skill", "Skill")
                        .WithMany("AgentSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Sayhi.Model.ChatMessage", b =>
                {
                    b.HasOne("Sayhi.Model.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sayhi.Model.Person", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Sayhi.Model.ChatParticipant", b =>
                {
                    b.HasOne("Sayhi.Model.Chat", "Chat")
                        .WithMany("Participants")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sayhi.Model.Person", "Person")
                        .WithMany("Chats")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Sayhi.Model.Group", b =>
                {
                    b.HasOne("Sayhi.Model.Agent", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Sayhi.Model.Queue", b =>
                {
                    b.HasOne("Sayhi.Model.Group", "Group")
                        .WithMany("Queues")
                        .HasForeignKey("GroupId");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Sayhi.Model.QueueAssignment", b =>
                {
                    b.HasOne("Sayhi.Model.Agent", "Agent")
                        .WithMany("QueueAssignments")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sayhi.Model.Queue", "Queue")
                        .WithMany("QueueAssignments")
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Queue");
                });

            modelBuilder.Entity("Sayhi.Model.QueueSkill", b =>
                {
                    b.HasOne("Sayhi.Model.Queue", "Queue")
                        .WithMany("QueueSkills")
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sayhi.Model.Skill", "Skill")
                        .WithMany("QueueSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Queue");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Sayhi.Model.Agent", b =>
                {
                    b.Navigation("AgentGroups");

                    b.Navigation("AgentSkills");

                    b.Navigation("QueueAssignments");
                });

            modelBuilder.Entity("Sayhi.Model.Chat", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Sayhi.Model.Group", b =>
                {
                    b.Navigation("AgentGroups");

                    b.Navigation("Queues");
                });

            modelBuilder.Entity("Sayhi.Model.Person", b =>
                {
                    b.Navigation("Agent");

                    b.Navigation("Chats");
                });

            modelBuilder.Entity("Sayhi.Model.Queue", b =>
                {
                    b.Navigation("QueueAssignments");

                    b.Navigation("QueueSkills");
                });

            modelBuilder.Entity("Sayhi.Model.Skill", b =>
                {
                    b.Navigation("AgentSkills");

                    b.Navigation("QueueSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
